/*!
The `hmm_tblout` crate is purely for parsing the output of
certain HMMER3 programs. The output is generated by passing
the `--tblout` flag to the HMMER3 program.

# Example

```no_run
use hmm_tblout;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    // get the command line args, only parse the
    // first one which should be a fasta file
    let args: Vec<String> = std::env::args().collect();
    if args.len() < 2 {
        println!("Usage: print_coordinates <tblout_file>");
        std::process::exit(1);
    }

    let reader = hmm_tblout::Reader::from_path(args[1].clone())?;

    for record in reader.into_records() {
        let r = record?;
        let tname = r.target_name();
        let strand = r.strand();
        let alifrom = r.ali_from();
        let alito = r.ali_to();

        println!("{}\t{}\t{}\t{}", tname, strand, alifrom, alito);
    }

    Ok(())
}
```
*/

mod error;
mod reader;
mod record;

pub use crate::{
    error::{Error, ErrorKind, Result},
    reader::{Reader, RecordsIntoIter, RecordsIter},
    record::{Meta, Program, Record},
};

#[cfg(test)]
mod tests {
    use super::*;

    fn b(s: &str) -> &[u8] {
        s.as_bytes()
    }

    const NHMMER_FILE: &str = "# target name        accession  query name           accession  hmmfrom hmm to  alifrom   ali to  envfrom   env to   sq len strand   E-value  score  bias  description of target
#------------------- ---------- -------------------- ---------- ------- -------  -------  -------  -------  -------  ------- ------ --------- ------ ----- ---------------------
SUPER_1              -          TR                   -                1     315 10988331 10987997 10988331 10987995 52766903    -     6.5e-34  124.1   1.2  -
SUPER_3              -          TR                   -              139     204 17951382 17951472 17951359 17951492 49366223    +        0.74   15.6   3.0  -
SUPER_4              -          TR                   -               29     130 20542008 20542119 20541989 20542141 47284787    +         1.1   15.1   5.7  -
SUPER_4              -          TR                   -               29     126 32993383 32993283 32993398 32993263 47284787    -         2.2   14.1   1.0  -
SUPER_4              -          TR                   -               23     126 14861076 14861174 14861063 14861195 47284787    +         2.4   13.9   3.4  -
SUPER_5              -          TR                   -               21     126 27641355 27641256 27641369 27641229 46997258    -         2.5   13.8   6.5  -
SUPER_8              -          TR                   -              158     191 33162494 33162454 33162514 33162446 33878543    -         3.1   13.6   2.0  -
SUPER_5              -          TR                   -              107     162 46228956 46228885 46228975 46228876 46997258    -         3.1   13.6   0.0  -
SUPER_1              -          TR                   -               68     173 15697438 15697327 15697464 15697325 52766903    -         4.4   13.1   0.7  -
SUPER_3              -          TR                   -               24     128 36147201 36147098 36147221 36147078 49366223    -         4.5   13.0   1.9  -
SUPER_1              -          TR                   -                1      84 36988055 36987966 36988055 36987944 52766903    -         4.7   13.0   2.1  -
SUPER_6              -          TR                   -               38     122 20863320 20863225 20863338 20863202 43664244    -           5   12.9   2.2  -
SUPER_8              -          TR                   -                1      79 32349659 32349576 32349659 32349556 33878543    -         5.9   12.6   2.5  -
SUPER_2              -          TR                   -               22     128 38320620 38320502 38320631 38320480 52745556    -         6.5   12.5   0.0  -
SUPER_1              -          TR                   -                2      55  1602497  1602446  1602498  1602420 52766903    -         8.6   12.1   7.2  -
SUPER_2              -          TR                   -                2     100 26735237 26735139 26735238 26735122 52745556    -           9   12.0   1.4  -
#
# Program:         nhmmer
# Version:         3.4 (Aug 2023)
# Pipeline mode:   SEARCH
# Query file:      TR.hmm
# Target file:     /lustre/scratch124/tol/projects/darwin/data/dicots/Misopates_orontium/assembly/curated/daMisOron1.1/daMisOron1.1.primary.fa.gz
# Option settings: /software/team301/hmmer-3.4/src/nhmmer --tblout Misopates_orontium.tbl --dna --cpu 10 TR.hmm /lustre/scratch124/tol/projects/darwin/data/dicots/Misopates_orontium/assembly/curated/daMisOron1.1/daMisOron1.1.primary.fa.gz
# Current dir:     /lustre/scratch123/tol/teams/blaxter/users/mb39/ARU/tr_detection
# Date:            Fri May  3 10:07:36 2024
# [ok]";

    #[test]
    fn test_whole_file() {
        let reader = Reader::from_reader(b(NHMMER_FILE));

        let first = reader.unwrap().records().next().unwrap().unwrap();

        assert_eq!(first.target_name(), "SUPER_1".to_string())
    }

    #[test]
    fn test_meta() {
        let reader = Reader::from_reader(b(NHMMER_FILE));
        let r = reader.unwrap();
        let meta = r.meta();
        assert_eq!(meta.program(), Program::Nhmmer);
        assert_eq!(meta.version(), "3.4 (Aug 2023)".to_string());
    }
}
